---
- name: Prepare stand for work, install packets
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: Upgrade distro
      yum:  
        name: '*'
        state: latest

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Install nano
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest 